name: CI

on:
  push:
    branches:
    - main

jobs:
  build_api:
    runs-on: ubuntu-20.04
    steps:
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: 'smartie-pants-API/SmartiePants.Api/appsettings.json'
      env:
        ConnectionStrings.Default: ${{ secrets.CONNECTION_STRING }}
    
    - uses: actions/checkout@v1
    - name: Build and deploy the Docker image
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'smartie-pants-api' }}
      run: |
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
